services:
  mysql:
    image: mariadb:10.8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mailer:
    image: axllent/mailpit
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  app:
    # image: php:7.4-cli
    build:
      context: .
      dockerfile: Dockerfile
    image: habitify
    container_name: habit-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
        - ./.env:/app/.env:ro
    environment:
      APP_ENV: prod
      APP_DEBUG: '0'
      APP_SECRET: '35cfa9cc3ecff75537f52b69f9976a97'
      DATABASE_URL: "mysql://root:root@mysql:3306/habit-tracker?serverVersion=mariadb-10.8.3&charset=utf8mb4"
      MAILER_DSN: "smtp://mailer:1025?encryption=&auth_mode=none"
    depends_on:
      - mysql
      - mailer
    command: >
      bash -lc "
        composer install --no-interaction &&
        php bin/console doctrine:database:create --if-not-exists &&
        php bin/console doctrine:migrations:migrate --no-interaction &&
        php bin/console doctrine:fixtures:load --no-interaction &&
        symfony serve --no-tls --allow-http --port=8000 --dir=public --allow-all-ip
      "
