services:
  mysql:
    image: mariadb:10.8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mailer:
    image: axllent/mailpit
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  app:
    image: php:7.4-cli
    build:
      context: .
      dockerfile: Dockerfile
    container_name: habit-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_URL: "mysql://root:root@mysql:3306/habit-tracker?serverVersion=mariadb-10.8.3&charset=utf8mb4"
    depends_on:
      - mysql
