<?php

namespace ContainerQa3x0To;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabitControllerselectHabitService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2L_CK2B.App\Controller\HabitController::selectHabit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2L_CK2B.App\\Controller\\HabitController::selectHabit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'selectedHabits' => ['privates', 'App\\Repository\\SelectedHabitsRepository', 'getSelectedHabitsRepositoryService', true],
        ], [
            'entityManager' => '?',
            'selectedHabits' => 'App\\Repository\\SelectedHabitsRepository',
        ]))->withContext('App\\Controller\\HabitController::selectHabit()', $container);
    }
}
