<?php

namespace ContainerQa3x0To;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabitControllerremoveHabitService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2kss0cR.App\Controller\HabitController::removeHabit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2kss0cR.App\\Controller\\HabitController::removeHabit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ownHabits' => ['privates', 'App\\Repository\\OwnHabitRepository', 'getOwnHabitRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'ownHabits' => 'App\\Repository\\OwnHabitRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\HabitController::removeHabit()', $container);
    }
}
