<?php

namespace ContainerQa3x0To;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrackHabitsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\TrackHabitsCommand' shared autowired service.
     *
     * @return \App\Command\TrackHabitsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/TrackHabitsCommand.php';

        $container->privates['App\\Command\\TrackHabitsCommand'] = $instance = new \App\Command\TrackHabitsCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\SelectedHabitsRepository'] ?? $container->load('getSelectedHabitsRepositoryService')), ($container->privates['App\\Repository\\TrackingRepository'] ?? $container->load('getTrackingRepositoryService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));

        $instance->setName('app:track-habits');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
