<?php

namespace ContainerQa3x0To;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrackHabitsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\TrackHabitsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\TrackHabitsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:track-habits', [], 'Add a short description for your command', false, #[\Closure(name: 'App\\Command\\TrackHabitsCommand')] fn (): \App\Command\TrackHabitsCommand => ($container->privates['App\\Command\\TrackHabitsCommand'] ?? $container->load('getTrackHabitsCommandService')));
    }
}
