<?php

namespace ContainerZvTz3FA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Wh1g1gGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wh1g1gG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wh1g1gG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\DashboardController::Habits' => ['privates', '.service_locator.mMHptox.App\\Controller\\DashboardController::Habits()', 'getDashboardControllerHabitsService', true],
            'App\\Controller\\HabitController::Habits' => ['privates', '.service_locator.mMHptox.App\\Controller\\HabitController::Habits()', 'getHabitControllerHabitsService', true],
            'App\\Controller\\HabitController::trackHabits' => ['privates', '.service_locator.vgnGu7f.App\\Controller\\HabitController::trackHabits()', 'getHabitControllertrackHabitsService', true],
            'App\\Controller\\HabitController::newHabit' => ['privates', '.service_locator.egipcEH.App\\Controller\\HabitController::newHabit()', 'getHabitControllernewHabitService', true],
            'App\\Controller\\HabitController::removeHabit' => ['privates', '.service_locator.2kss0cR.App\\Controller\\HabitController::removeHabit()', 'getHabitControllerremoveHabitService', true],
            'App\\Controller\\HabitController::selectHabit' => ['privates', '.service_locator.2L_CK2B.App\\Controller\\HabitController::selectHabit()', 'getHabitControllerselectHabitService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.wa9Zqkq.App\\Controller\\LoginController::index()', 'getLoginControllerindexService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.yI4423g.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.KHhLDTq.App\\Controller\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\DashboardController:Habits' => ['privates', '.service_locator.mMHptox.App\\Controller\\DashboardController::Habits()', 'getDashboardControllerHabitsService', true],
            'App\\Controller\\HabitController:Habits' => ['privates', '.service_locator.mMHptox.App\\Controller\\HabitController::Habits()', 'getHabitControllerHabitsService', true],
            'App\\Controller\\HabitController:trackHabits' => ['privates', '.service_locator.vgnGu7f.App\\Controller\\HabitController::trackHabits()', 'getHabitControllertrackHabitsService', true],
            'App\\Controller\\HabitController:newHabit' => ['privates', '.service_locator.egipcEH.App\\Controller\\HabitController::newHabit()', 'getHabitControllernewHabitService', true],
            'App\\Controller\\HabitController:removeHabit' => ['privates', '.service_locator.2kss0cR.App\\Controller\\HabitController::removeHabit()', 'getHabitControllerremoveHabitService', true],
            'App\\Controller\\HabitController:selectHabit' => ['privates', '.service_locator.2L_CK2B.App\\Controller\\HabitController::selectHabit()', 'getHabitControllerselectHabitService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.wa9Zqkq.App\\Controller\\LoginController::index()', 'getLoginControllerindexService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.yI4423g.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.KHhLDTq.App\\Controller\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\DashboardController::Habits' => '?',
            'App\\Controller\\HabitController::Habits' => '?',
            'App\\Controller\\HabitController::trackHabits' => '?',
            'App\\Controller\\HabitController::newHabit' => '?',
            'App\\Controller\\HabitController::removeHabit' => '?',
            'App\\Controller\\HabitController::selectHabit' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\DashboardController:Habits' => '?',
            'App\\Controller\\HabitController:Habits' => '?',
            'App\\Controller\\HabitController:trackHabits' => '?',
            'App\\Controller\\HabitController:newHabit' => '?',
            'App\\Controller\\HabitController:removeHabit' => '?',
            'App\\Controller\\HabitController:selectHabit' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
        ]);
    }
}
