<?php

namespace ContainerZvTz3FA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MMHptoxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mMHptox' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mMHptox'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trackings' => ['privates', 'App\\Repository\\TrackingRepository', 'getTrackingRepositoryService', true],
            'sh' => ['privates', 'App\\Repository\\SelectedHabitsRepository', 'getSelectedHabitsRepositoryService', true],
        ], [
            'trackings' => 'App\\Repository\\TrackingRepository',
            'sh' => 'App\\Repository\\SelectedHabitsRepository',
        ]);
    }
}
