<?php

namespace ContainerZvTz3FA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabitControllertrackHabitsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vgnGu7f.App\Controller\HabitController::trackHabits()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vgnGu7f.App\\Controller\\HabitController::trackHabits()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'sh' => ['privates', 'App\\Repository\\SelectedHabitsRepository', 'getSelectedHabitsRepositoryService', true],
            'trackings' => ['privates', 'App\\Repository\\TrackingRepository', 'getTrackingRepositoryService', true],
        ], [
            'entityManager' => '?',
            'sh' => 'App\\Repository\\SelectedHabitsRepository',
            'trackings' => 'App\\Repository\\TrackingRepository',
        ]))->withContext('App\\Controller\\HabitController::trackHabits()', $container);
    }
}
