<?php

namespace ContainerZvTz3FA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOwnHabitTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\OwnHabitType' shared autowired service.
     *
     * @return \App\Form\OwnHabitType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/OwnHabitType.php';

        return $container->privates['App\\Form\\OwnHabitType'] = new \App\Form\OwnHabitType();
    }
}
