<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCgdtQnR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCgdtQnR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCgdtQnR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCgdtQnR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCgdtQnR\App_KernelDevDebugContainer([
    'container.build_hash' => 'CgdtQnR',
    'container.build_id' => '60527eb4',
    'container.build_time' => 1745948972,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCgdtQnR');
