<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOgJLVuK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOgJLVuK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOgJLVuK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOgJLVuK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOgJLVuK\App_KernelDevDebugContainer([
    'container.build_hash' => 'OgJLVuK',
    'container.build_id' => 'c6a9afd8',
    'container.build_time' => 1746898298,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOgJLVuK');
