<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHeIynsA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHeIynsA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHeIynsA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHeIynsA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHeIynsA\App_KernelDevDebugContainer([
    'container.build_hash' => 'HeIynsA',
    'container.build_id' => '0195512a',
    'container.build_time' => 1747147968,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHeIynsA');
